puphpet.extension.nginx.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionNginxBundle:Front:index }

puphpet.extension.nginx.upstream:
    pattern:  /upstream
    defaults: { _controller: PuphpetExtensionNginxBundle:Front:upstream }

puphpet.extension.nginx.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetExtensionNginxBundle:Front:vhost }

puphpet.extension.nginx.location:
    pattern:  /location/{vhostId}
    defaults: { _controller: PuphpetExtensionNginxBundle:Front:location }

puphpet.extension.nginx.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionNginxBundle:Manifest:index }

